### ISSUE TITLE
Download doesn't work with ESR 45

### ISSUE THREAD

**Issue by SilvanScherrer** [bitwiseworks/mozilla-os2#201] opened 2017-04-26 13:06 UTC
[stdout.txt](https://github.com/bitwiseworks/mozilla-os2/files/958427/stdout.txt)
this is the console output of doing the following:
- start ESR45
- goto rpm.netlabs.org/test
- download emxomfld.exe
- open the download container (there it shows the file with status failed)
- closing ESR45

**Comment by dmik** [comment] 2017-04-27 18:29
BTW, another problem with directory creation is when you try to start FF with the Profile dir deleted/renamed. It fails to create a new one and shows you the Profile selection dialog but when you press Create Profile... you eventually get this:
```
Profile couldn't be created. Probably the chosen folder isn't writable.
[Exception... "Component returned failure code: 0x80520008 (NS_ERROR_FILE_ALREADY_EXISTS) [nsIToolkitProfileService.createProfile]"  nsresult: "0x80520008 (NS_ERROR_FILE_ALREADY_EXISTS)"  location: "JS frame :: chrome://mozapps/content/profile/createProfileWizard.js :: onFinish :: line 201"  data: no]
```
This looks similar to what Silvan experiences. 

Also, @ydario noticed that if he rolls back NSPR to pre-kLIBC changes (i.e. when Dos APIs are used directly) all starts working well. So I suspect a regression in this NSPR change: http://trac.netlabs.org/ports/changeset/2186. Investigating now.

**Comment by dmik** [comment] 2017-04-27 21:49
The profile creation issue is most likely caused by a strange fact that `prefs.js` in the user profile is created as a symlink for some reason (and this symlink leads to the mozilla git tree). Weird.

**Comment by dryeo** [comment] 2017-04-27 22:54
Similar problem creating a new profile with SeaMonkey except 
mimetypes.rdf is symlinked to the source tree.
Can't save files either with either SM or TB including older versions 
that are using the NSPR I built from SVN

**Comment by dmik** [comment] 2017-04-28 00:39
I can confirm — using the SVN build of NSPR with Firefox 38 gives similar problems with downloads and all. But I still can't figure out where it goes wrong.

**Comment by dmik** [comment] 2017-04-29 11:36
The source of the problem is replacement of `DosOpen` with kLIBC `open`. However, still not clear what goes wrong.

**Comment by dmik** [comment] 2017-05-02 13:00
I found it, stupid regression from my NSPR update, lost PR_CREATE_FILE flag processing. Fixed in NSPR, see http://trac.netlabs.org/ports/changeset/2187/nspr. Now downloading works and profile creation works too.

However, the new FF still creates symlinked files in a new profile. I don't think it's anyhow related to NSPR, it's something else. Created #203 for it.

**Closed by dmik** 2017-05-02 13:00 UTC

**Comment by SilvanScherrer** [comment] 2017-05-02 13:18
I can confirm it works
