### ISSUE TITLE
FF 31.8.0 Opens New FF

### ISSUE THREAD

**Issue by babydoc** [bitwiseworks/mozilla-os2#127] opened 2015-07-30 20:48 UTC
Whenever I click a link to a URL from TB, FF opens a new instance of itself rather than a new tab (as I have set it to do).

**Comment by LewisR** [comment] 2015-07-30 21:21
Sounds like #125. Dupe?

**Comment by babydoc** [comment] 2015-07-30 21:45
Lewis

> Sounds like #125
> <https://github.com/bitwiseworks/mozilla-os2/issues/125>. Dupe?

It may be. Steven said that FF opens in a new window. I said it opens a 
new instance of the program. I guess that is the same?

Martin

**Comment by LewisR** [comment] 2015-07-30 21:55
From a UI perspective, Martin, then result is the same (new window). If you are actually seeing multiple firefox.exe entries in your list of running programs, that may be another. I suspect, however, that this is the same as Steve is describing, as it's non-trivial to actually run multiple instances of these programs (FF, SM, TB, etc.) simultaneously.

**Comment by babydoc** [comment] 2015-07-30 22:03
>  From a UI perspective, Martin, then result is the same (new window). If
> you are actually seeing multiple firefox.exe entries in your list of
> running programs, that may be another. I suspect, however, that this is
> the same as Steve is describing, as it's non-trivial to actually run
> multiple instances of these programs (FF, SM, TB, etc.) simultaneously.

It is multiple FF windows with one running program. I should have 
checked. I hope it gets fixed because it is annoying.

Martin

**Comment by LewisR** [comment] 2015-07-30 22:12
Understandably so! Per my mention in #125, SM seems to behave as expected, so this appears to be a FF-only issue.

**Comment by dmik** [comment] 2015-07-31 10:00
@babydoc thank you for clarification, it was important whether there were multiple `firefox.exe` processes or just multiple windows of the same process. The latter makes it a duplicate of #125, closing.

**Closed by dmik** 2015-07-31 10:00 UTC
