### ISSUE TITLE
Download file nr 3 exits FF

### ISSUE THREAD

**Issue by JoopN** [bitwiseworks/mozilla-os2#118] opened 2015-07-25 13:10 UTC
Vendor=Mozilla
Name=Firefox
Version=31.8.0
BuildID=20150724032810

As soon as you want to download file number 3 the system crashes or exits the fast way.

**Comment by dbanet** [comment] 2015-07-25 13:17
Can't reproduce: just have successfully downloaded three MP3s in a row.

**Comment by JoopN** [comment] 2015-07-25 14:49
I can't, what files are involved with downloading.

Op 25-07-15 15:17, dbanet schreef:

**Comment by JoopN** [comment] 2015-07-25 15:43
Tried with a complete clean FF 31.8.0 and with third download system 
exit hard. Its going that fast that no log is written anywhere.
I tried again on SourceForge and did change directories there, that 
might be different if you stay in one directory and download multiple 
files.
For the record, I don't know where too look for in pinpointing the 
problem. I can do it over and over again with same results. With old 
data previous FF, with complete clean installation and new profile. The 
only thing I can think of is not FF related but something in dll files. 
But if that's the case I need a dll file name to look for. I'm out of 
options.

Regards,
Joop

Op 25-07-15 15:17, dbanet schreef:

**Comment by StevenLevine** [comment] 2015-07-26 04:51
How are you starting firefox?  How are you installing the firefox prerequisites?  Are you sure your exceptq install is working?

**Comment by JoopN** [comment] 2015-07-26 18:55
Hello Steve,

I use run! for start

This is my Firefox!.env file;
rem SET MOZILLA_HOME=P:\FIREFOX_PROFIEL_3180x
SET MOZ_PLUGIN_PATH=I:\FIREFOX_PLUGINS
rem SET ICEDTEA_WEB_JRE=I:\JAVA\JAVA160ga5
SET NSPR_OS2_NO_HIRES_TIMER=1
SET MOZ_ACCELERATED=1
rem SET MOZ_NO_REMOTE=1

Note; the rem on the first line did force FF to make a new profile. My 
profiles are all on drive P: with own directory

I start FF with Firefox!EL.EXE

I use run! because I use different FF next to each other, has to do with 
that not every JAVA program has been programmed the right way. So 
sometimes error=2 or no help or something that need the browser.
For some reason FF602 does pickup things and later not. FF2481 looks 
promising. Versions in between something broke somewhere (tested with 
JAlbum).

FF downloaded as zip and unzipped in new directory firefox_xxxx, where 
the xxxx are replaced by version number.

Prerequisites are downloaded in zip and dll's are copied to \ecs\dll 
directory. This directory is in the config.sys.

This setup always worked for xpi files. So I'm puzzled.

Don't have exceptq installed as it is no prerequisite, but more nice to 
have. Will look into it.

Regards,
Joop


Op 26-07-15 06:51, StevenLevine schreef:

**Comment by StevenLevine** [comment] 2015-07-26 21:45
>I start FF with Firefox!EL.EXE

Use Firefox!EGL.exe and check if the log file reports anything helpful.

>This setup always worked for xpi files. So I'm puzzled.

Stuff breaks.  There is some sort of non-obvious issue in your setup.

>Don't have exceptq installed as it is no prerequisite,

It is a prerequisite if you have problems with your setup.

**Comment by JoopN** [comment] 2015-07-27 00:28
Op 26-07-15 23:45, StevenLevine schreef:
>
>> I start FF with Firefox!EL.EXE
>
> Use Firefox!EGL.exe and check if the log file reports anything helpful.
>
Enclosed log file.

Regards,
Joop

DIVE forced on by MOZ_ACCELERATED=1 - pointer will be hidden
_init_dive:  _load_dive() succeeded
_init_dive:  hDive= 1  scrn= 0x4aa0000  format= BGR4
Changing DIVE from enabled to disabled - 'layers.acceleration.disabled' is TRUE
1437956623050	addons.xpi	WARN	Failed to install J:\eCS\COMMUNICATIE\FIREFOX\nl_3180.xpi from file:///J:/eCS/COMMUNICATIE/FIREFOX/nl_3180.xpi: {"operation":"stat","path":"I:\\FIREFOX_3180\\Mozilla\\Firefox\\Profiles\\1wu4ef09.default\\extensions\\staged\\langpack-nl@firefox.mozilla.org.xpi","unixErrno":0}

**Comment by JoopN** [comment] 2015-07-27 01:01
Op 26-07-15 23:45, StevenLevine schreef:
>
>> I start FF with Firefox!EL.EXE
>
> Use Firefox!EGL.exe and check if the log file reports anything helpful.
>
Enclosed the logfile I get with download file nr 3 exit.

Regards,
Joop

DIVE forced on by MOZ_ACCELERATED=1 - pointer will be hidden
_init_dive:  _load_dive() succeeded
_init_dive:  hDive= 1  scrn= 0x4aa0000  format= BGR4
Changing DIVE from enabled to disabled - 'layers.acceleration.disabled' is TRUE

FIREFOX.EXE:
Abnormal program termination
RWSCLI08: RwsExitListProc - termination code= 0

FIREFOX.EXE:
Abnormal program termination

**Comment by dryeo** [comment] 2015-07-27 02:40
@JoopN can you add set MOZ_NO_REMOTE=1 to your environment and retest 
downloading files?

**Comment by StevenLevine** [comment] 2015-07-27 04:54
I'd also recommend

  `SET MOZ_NO_RWS=1`

just in case.

@JoopN, did Firefox generate a .trp file?

**Comment by dryeo** [comment] 2015-07-27 04:57
On 07/26/15 09:54 PM, StevenLevine wrote:
> I'd also recommend
>
> |SET MOZ_NO_RWS=1|
>

Brainfart, that's what I meant to write

**Comment by dmik** [comment] 2015-07-27 17:20
I tried downloading five or six several-hundred-MB files from sourceforge — all worked smoothly. Please provide more details and a TRP file of your crash.

**Comment by JoopN** [comment] 2015-07-28 00:04
Dmitriy,

Thanks, tested the trap system, works, but FF produce no trp files.


Op 27-07-15 19:20, Dmitriy Kuminov schreef:

**Comment by JoopN** [comment] 2015-07-28 00:08
Dave,

in the readme;
"* MOZ_NO_REMOTE=1
This permits you to run multiple copies of the same app at the same time 
(provided you have separate profiles for each copy). Also works as a 
parameter, eg Firefox -no-remote"

What has this to do with FF exit on download nr 3? I don't understand this.


Op 27-07-15 04:40, Dave Yeo schreef:

**Comment by JoopN** [comment] 2015-07-28 00:14
Op 27-07-15 06:54, StevenLevine schreef:
> I'd also recommend
>
>    `SET MOZ_NO_RWS=1`
>
> just in case.

Don't understand this one, explanation in readme point to something else 
and not to download. But I will try.
>
> @JoopN, did Firefox generate a .trp file?

No, the only thing I have is the log from FF. Tested exceptq with the 
test files and that worked.

**Comment by dryeo** [comment] 2015-07-28 00:46
Sorry Joop, I meant to write set moz_no_rws=1. Shouldn't post when tired :)

**Comment by dryeo** [comment] 2015-07-28 00:50
On 07/27/15 05:14 PM, JoopN wrote:
> Op 27-07-15 06:54, StevenLevine schreef:
>  > I'd also recommend
>  >
>  > `SET MOZ_NO_RWS=1`
>  >
>  > just in case.
>
> Don't understand this one, explanation in readme point to something else
> and not to download. But I will try.

RWS allows using the WPS associations. There are lots of problems caused 
by this with mail attachments and occasionally downloads. At one point 
every time I downloaded a tar.gz, the browser would crash.
I even wonder if it should be disabled by default. When I complained to 
Rich about TB crashing due to RWS, he just said it was kind of a hack.

**Comment by StevenLevine** [comment] 2015-07-28 01:37
>Thanks, tested the trap system, works, but FF produce no trp files.

Try

  `SET EXECPTQ=Z`

See the "Report normal terminations" section of exceptq-shl.txt.  What
might be happening is that firefox is issuing a DosExit() for an as yet
unknown reaason, rather than trapping.  This exceptq option will produce a
.trp file if this is the case.

**Comment by JoopN** [comment] 2015-07-30 00:21
Thanks Steve,
I have it now in the Firefox!.ENV file, but still no trp files. Wrong 
file and put it in config.sys?


Op 28-07-15 03:37, StevenLevine schreef:

**Comment by StevenLevine** [comment] 2015-07-30 00:47
>I have it now in the Firefox!.ENV file, but still no trp files. Wrong 
>file and put it in config.sys?

The .env file is a good place for the setting.  The problem is there is a
typo

  SET EXECPTQ=Z

should be

  SET EXCEPTQ=Z

Sorry.

**Comment by JoopN** [comment] 2015-07-31 09:57
Hi Steve,
Those things happen, I will try again.

Op 30-07-15 02:47, StevenLevine schreef:

**Comment by dmik** [comment] 2015-07-31 11:41
@JoopN could you please make sure the problem is still there? As it could be also related to different incompatible `libc06*` versions floating around on your machine.

**Comment by JoopN** [comment] 2015-07-31 14:22
I have followed your mail and verified your listing with mine. There where two libc files with not the right date and with your instructions I replaced them. Followed instructions from Steve. Today tried again, file nr 3 exits hard and fast. There is no trp file (that system works because the test does trigger trp files).  Checked the drive, the only libc*.* are in my  \os2\dll directory. 
The only thing I have in the log file is:
DIVE forced on by MOZ_ACCELERATED=1 - pointer will be hidden
_init_dive:  _load_dive() succeeded
_init_dive:  hDive= 1  scrn= 0x2aa0000  format= BGR4
Changing DIVE from enabled to disabled - 'layers.acceleration.disabled' is TRUE

FIREFOX.EXE:
Abnormal program termination

FIREFOX.EXE:
Abnormal program termination

That is it.

**Comment by JoopN** [comment] 2015-08-01 14:51
Did some tests today, the results are that it seems having to do with file sizes or with the length of file names. The downloaded files are 8.3 and the first 3 are 782k, 328k and 560k, the last fourth file is only 75k.
FF 6.02 could download the 4 files without problems
FF 10.0.11 could download the 4 files without problems
FF 17.0.11 could download the 4 files without problems
FF 24.8.1 could download the 4 files without problems
FF 31.8.0 could download the first 3 files, on the fourth hard exit.
Seems that more has to be adjusted then outlined in readme.os2!
Free shared memory is around 180mb after all this. 
I've eCS1.2Dutch P4 2.8Ghz, 1Gb memory, plenty free on harddisk, in case you have questions about it. I'm puzzled with these results, could it be a setting, I've not changed much on settings with 31.8.0 and its still on the test profile. Between the test with the different FF nothing has changed. It was loading, downloading and exit. All have own directories and own profile directories,  so no mixing up data or programs between the FF installations. May be this is of some help.

**Comment by dmik** [comment] 2015-08-01 15:28
Are you sure you completely sorted out the libc06* problem? I have no idea what else it could be. May be some network problems... And since there is even no other reports confirming this I don't see what we can do about that ATM.

Well, the one thing you can try is set `toolkit.osfile.log` to `true` in `about:config` and upload the full console output of your failed download attempt to gist.

**Comment by JoopN** [comment] 2015-08-01 16:40
These are the libc's on my system
14-04-04 16:37        356.330    236 ----  libc05.dll
26-10-14 20:17         48.179    236 ----  libc06.dll
26-10-14 20:17         48.179    236 ----  libc061.dll
26-10-14 20:17        157.161    236 ----  libc062.dll
26-10-14 20:17        157.161      0 a---  libc063.dll
26-10-14 20:17        157.213    236 ----  libc064.dll
26-10-14 20:17        157.213    236 a---  libc065.dll
26-10-14 20:16      1.361.666      0 ----  libc066.dll
22-11-99 11:45        210.916      0 ----  LIBCM.DLL
22-11-99 11:45         57.340    236 ----  LIBCN.DLL
22-11-99 11:45        192.386    236 ----  LIBCS.DLL

The only thing I can think off is deleting libc05.dll, but don't know 
what will go wrong then. My guess is that ff looks for libc06x.dll. The 
last three are from the eCS1.2 installation. The ones with an "a" are 
the ones which I replaced according your instructions. Both where 
locked, so with installation of libc066 something did get wrong.
Will set it to true and see what the log will tell.


Op  1-08-15 17:28, Dmitriy Kuminov schreef:

**Comment by SilvanScherrer** [comment] 2016-03-02 13:37
please retry with ffox 38

**Comment by SilvanScherrer** [comment] 2016-08-15 17:01
The author tried 38 and opened #187. So I close this as duplicate

**Closed by SilvanScherrer** 2016-08-15 17:01 UTC
Labels: task, tests
