### ISSUE TITLE
Decide on native printer support

### ISSUE THREAD

**Issue by dmik** [bitwiseworks/mozilla-os2#155] opened 2016-02-21 17:55 UTC
Currently, printing using the native printer drivers is disabled, see #147. We need to decide what to do with it. We have two options:

1. Add OS/2 GPI printing to Cairo 1.12, re-enable it in Firefox and fix bugs #75 and #134.
2. Drop GPI printing at all and instead use CUPS for that. This also requires adoption of the Print Dialog to CUPS specifics (to allow for proper setup of all key printing options etc.).

**Comment by dmik** [comment] 2016-02-21 17:58
So far, my personal vote goes for CUPS. When compared to native GPI, the only drawback I see is that the user needs to install CUPS and add CUPS printers (but if the system uses YUM/ANPM it will be a no issue). Other than that, native GPI loses here: lower print quality, no modern printer support etc etc. CUPS is a modern, constantly developed system that supports every printer on planet.

**Comment by dbanet** [comment] 2016-02-22 05:50
Uhm, what there is a native OS/2 printer driver for a printer not supported otherwise?

Will it be possible to print to it with exclusive CUPS support?

**Comment by dmik** [comment] 2016-02-24 09:36
I doubt there is a printer supported by OS/2 and not supported by CUPS. If you know such, please gives us a name.

**Comment by LewisR** [comment] 2016-02-24 18:21
The problem is different for larger enterprises where CUPS installation and administration adds another layer (barrier) to providing a modern browser.

Case in point: I have a consulting client which is a large home products manufacturer and packager (home products=cleaners, laundry detergent, hand soap). The entire operation runs on OS/2, with printing handled through NetWare queues. A browser is needed for access to the company intranet. While browser security is less of an issue, it is unknown to me when or if the company intranet may utilize @font-face glyphs on/in any of their content, so being able to provide a legible, working browser is a requirement.

While adding CUPS is not insurmountable, it requires rolling it out to 80-100 stations, configuring it (currently, the local parallel port is captured to the NetWare queue upon login), and then being able to deal with any printer changes going forward. This is less than desirable, from my perspective, at least.

As to whether there exist any printers which are not supported by CUPS but which are supported by native printing, I can't think of a good example, unless there are some plotters or old dot matrix models(!) still in use.

**Comment by valerius2k** [comment] 2016-02-24 22:15
"Old" dot matrix printers are still used everywhere in stocks, customs and for printing checks in any stores. So, it still widely used. These printers are called "special purpose" printers instead of matrix printers. All major printer vendors still continue producing such printers.

Also, I have DJ 920c inkjet printer which has native OS/2 drivers which are high quality. Also, as far as I know, CUPS is working itself via a GPI driver -- cups.pdr. So, GPI doesn't go away even with CUPS. I am still didn't used CUPS as I can avoid using it so far. Though, I use some Ghostscript print filters, via lprportd.

So, I would support Lewis' opinion, as I like a minimum of intermediate layers needed. Though, CUPS would be probably, a simpler solution, and it is used in Qt too.

**Comment by dmik** [comment] 2016-02-25 10:58
@LewisR I get your point. If you talk about **existing** customers — yes, dropping GPI printing will make some problem. But again, if we talk about Blue Lion :) the RPM env will be there by default so installing CUPS is not a big deal and I'm sure installing a CUPS printer can also be automated... But may be I look to far into the future, I can agree to that.

@valerius2k are there native GPI drivers for such printers? As for matrix printers in general, CUPS has very good support for them IIRC. As for DJ 920c, did you try printing to it through CUPS? As for GPI drivers, cups.pdr IIRC only provides some basic functionality, the rest is done through PS which is sent to the printer by CUPS.

**Comment by valerius2k** [comment] 2016-02-26 02:20
Of course, there are GPI drivers for matrix printers, for example, emson.drv, IBM Proprinter etc. For DJ 920c -- no, I didn't tried CUPS as I have good native drivers.

**Comment by dspiatkowski** [comment] 2016-02-26 04:16
...and what about those situations where the current PSCRIPT and/or PSPRINT
drivers do offer a very workable solution?

Case in point, I have replaced my old & trusty Brother Hl-1650 laser printer
with a Brother HL-5470DW model...so far (printer has been in use for barely a
month now) there is only one feature which does not work, that being a hybrid
1200 dpi mode (HQ1200), whereas all other features seem to work great.

Anyways...point being that as best as I can tell, CUPS installation might
deliver the missing HQ1200 mode (not all that important since the max res mode
of 1200 dpi works great), but otherwise, it's the same thing as what I have
right now.

Thanks,
-Dariusz

**Comment by dmik** [comment] 2016-02-26 10:32
@valerius2k you didn't get my question. You talked about special purpose matrix printers and I asked you whether these printers are natively supported by OS/2 including all their special functions.

**Comment by valerius2k** [comment] 2016-02-28 02:47
dmik, I did not set up such printers, but I don't know why they should be different than any other matrix printers which mostly use epson.drv.

**Comment by ak120** [comment] 2016-03-02 22:06
CUPS port lacks usable support for local connected printers (via serial or parallel port) - setting up for each location a lpd is a terrible way - next problem is missing support for system codepages, a lot of non-english OS/2 users can only print the test page currently with cups (in a fine quality of course) but nothing else.

**Comment by dmik** [comment] 2016-03-03 14:21
@ak120 it looks like you didn't manage to install CUPS correctly (or may be it's some bug in some version of something). I see no problems in connecting to local printers through CUPS, after all, to the GPI it looks like a normal postscript printer (which can be connected to any port which is supported by OS/2). I also didn't notice any problems with codepages (my OS/2 is Russian and all works fine).

So, please, could you please be more specific and open a respective ticket at http://trac.netlabs.org/ecups? Discussing CUPS bugs is off topic here. Thanks!

**Comment by SilvanScherrer** [comment] 2016-05-27 07:48
On WSE we also brought up this question and did a final decision. We will do CUPS and native printer support. As the decision is done we close this issue and opened #170 and #171 as a replacement.

**Closed by SilvanScherrer** 2016-05-27 07:48 UTC
Labels: question, task
