### ISSUE TITLE
Firefox 45.9 & Youtibe

### ISSUE THREAD

**Issue by holgerarif** [bitwiseworks/mozilla-os2#242] opened 2017-10-11 09:49 UTC
I installed Firefox 45.9 and have issues trying to watch youtube videos.
The youtube page itself is loaded rather slowly. Clicking on a video will bring up the video but mostly I receive the message : if playbach does not begin shortly,try restarting your device. According to suggestions at os2world I tried with new profile and no addons but the result remains the same.
For example : https://www.youtube.com/watch?v=B51A6bcMeDY does not work
Some videos do work, for example : https://www.youtube.com/watch?v=Hy8_ByqQA3Q
Regards
Holger

**Comment by dmik** [comment] 2017-10-11 10:15
Well, the first time I tried — it didn't work indeed, giving the same message you get. But reloading the page fixed it. So both videos play here now.

Note that you can right click on the video and select "statistics for sysadmins" from the bottom to get a nice overlay with codec and network statistics. When the first video was stuck, I saw that it didn't have any "host" assigned in that overlay (the corresponding line in the stats was empty). Reloading the page brought a host and the video playback.

**Comment by holgerarif** [comment] 2017-10-11 10:59
Hi dmik,
thank you for the reply, but it does not work here. I took a look at the statistics: In my case it seems to be the opposite. In the first video (Stones) I do get a host shown, in the second video there is no host shown?

**Comment by dmik** [comment] 2017-10-11 11:13
I have no idea on why it could give you problems. Doesn't look Firefox/2 related so far. May be it's related to your network problems or such. I'm closing this until more evidence of relation is available. Feel free to re-open if you diagnose anything new.

You may check older FF versions on OS/2 and the same FF version on other systems in the mean time.

**Closed by dmik** 2017-10-11 11:13 UTC

**Comment by dspiatkowski** [comment] 2017-10-11 12:38
Team,
I can confirm what Holger reported. I am seeing the same behaviour here. In my case, re-loading the video does not work either.

See the attached image for the capture of the stat data which dmik asked for...it does show the host, shows a good line speed as well (I recently upgraded to 120 Mb/s), but the video simply never starts.
Thanks,
 - Dariusz
![ff45_9-youtube_video_playback](https://user-images.githubusercontent.com/9026330/31440930-941b6cc4-ae5f-11e7-817b-2971c261ea45.jpg)

**Comment by dspiatkowski** [comment] 2017-10-12 14:52
I realize the ticket is closed, but we have at least a few people that are seeing the very same problem.

Further debugging of this issue on my part appears to show that somehow the 'Network Activity' showing a 0kB is indicative of the halt in the video playback. So in the previous screenshot, even though the connection speed is great and buffer health appears OK you will notice that Network Activity remains 0 kB.

Here is another URL showing this behaviour: https://youtu.be/MAigQuoCfD0

I have not been able to play ANY of the YouTube videos since going to 45.9 release here.

Thanks!

**Comment by dspiatkowski** [comment] 2017-10-12 15:26
OK, one last update in the "food for thought" stream...I finally hit a video that actually played.

At first it came up with an intermittent sound, basically the audio would cut out every couple of seconds, followed by a silence, followed be a returned playback. I then grabbed the stat info (see attachment) and paused the video. Upon re-starting it, the video continued with no more cutouts, playback was normal, back to the pre 45.9 release builds behaviour.

URL => https://www.youtube.com/watch?v=W8LhYVkrVmI&feature=youtu.be

![ff45_9-youtube_video_playback_working](https://user-images.githubusercontent.com/9026330/31504290-fc0a8474-af3f-11e7-8680-33d91749c059.jpg)
