### ISSUE TITLE
Trap in printing with FF 31.8.0

### ISSUE THREAD

**Issue by GAnchieri** [bitwiseworks/mozilla-os2#131] opened 2015-08-09 10:02 UTC
I have a USB HP PSC 1610 all in one printer, I was unable to print using native HP Deskject 660c printer drivers, because FF trap immediately. I attach the file: 0044_01.TRP obtained.

**Comment by dryeo** [comment] 2015-08-09 16:50
No trp file. You need to post it somewhere else and leave a pointer to it, perhaps as a gist.
This is probably a dupe of issue #75.

**Comment by GAnchieri** [comment] 2015-08-09 19:27
I have post a trap file using gist: 
GAnchieri / e:\programs\firefox\0044_01.trp

**Comment by dryeo** [comment] 2015-08-09 20:53
You need to post the actual URL, https://gist.github.com/GAnchieri/43b2d60c9fd1301f6e54

**Comment by GAnchieri** [comment] 2015-08-10 08:13
Thank you Dryeo, but I'm new using gist, normally other site use to upload the file together the issue, ie: netlabs.org

**Comment by dmik** [comment] 2015-08-10 09:57
I believe it's the same as #75. Thanks for reporting though.

**Closed by dmik** 2015-08-10 09:57 UTC
