### ISSUE TITLE
Addons fail to install/update

### ISSUE THREAD

**Issue by JanErikLaerka** [bitwiseworks/mozilla-os2#132] opened 2015-08-10 18:45 UTC
I always update my Firefox installation and use the existing profile with the new version to get my saved passwords, open tabs etc. with me. (Remove all but firefox!k.exe, firefox.exe and firefox.ico and unzip the new version to that same folder)

When updating from 24.8.1 to 31.8B5 it detect and for the first time also find the Language support (Swedish) and offer to install it. I've previously always had to search the web for the place where they store sv_SE.xpi and install it manually. Firefox now download the file and process it, but fail with information that it can't modify the needed file.

I've since removed the "old" language pack to see if that would help, in case it locked something, but no I just get 
![cantmodifyneedfile](https://cloud.githubusercontent.com/assets/13735819/9179942/eab68f0e-3f9f-11e5-91ef-ca18d489298b.png)
"Svenska  (SE) Language Pack could not be installed because 
Firefox cannot modify the needed file."

The problem also seem to affect other addons that fail with 
![adblockplusupdatefail](https://cloud.githubusercontent.com/assets/13735819/9179943/eabb4620-3f9f-11e5-910d-c56d86cb1914.png)
"There was an error installing Adblock Plus. Try again"

Language pack to start from:
ftp://ftp.mozilla.org/pub/firefox/releases/24.8.1esr/win32/xpi/sv-SE.xpi
Language pack to go to:
ftp://ftp.mozilla.org/pub/firefox/releases/31.8.0esr/win32/xpi/sv-SE.xpi

Conclusion, this doesn't seem to be limited to language packs, but to all addons.

**Comment by dmik** [comment] 2015-08-10 20:04
Seems like there is one more person having a `libc06*` mess on his computer. Please try what I describe in a similar (and already closed defect) here: https://github.com/bitwiseworks/mozilla-os2/issues/117#issuecomment-126077834.

Please report if it helps and feel free to reopen this issue if it doesn't. Closing it for now.

**Closed by dmik** 2015-08-10 20:04 UTC

**Comment by JanErikLaerka** [comment] 2015-08-10 21:06
Hello,

I have just installed eComStation v2.2 Beta.
Should we try to persuade XEU to alter something in eCS to get away from
these manual cleanup requirements.

2015-08-10 22:04 GMT+02:00 Dmitriy Kuminov <notifications@github.com>:

**Comment by dmik** [comment] 2015-08-10 21:26
There is a conceptual problem there: not all eComStation components use RPM for installing themselves. And RPM/YUM is of course unable to control stuff that was not installed with it (including version conflict solving and cleanup). There are some technical difficulties in doing that, apparently. But you may file a complain, it won't hurt.

As a temporary solution, you may make sure `%UNIXROOT%\usr\local\lib;%UNIXROOT%\usr\lib` (where %UNIXROOT% is the value of the UNIXROOT variable on your system, normally the boot drive, like `C:`) comes first in `LIBPATH` in your `config.sys`. Perhaps, I should put this to README.OS2.

**Comment by JanErikLaerka** [comment] 2015-08-10 21:34
I tend not to touch my installation of eComstation, just zap it and format
the drive and then install it fresh, just as this time.

So the problem is very much related to how eCS v2.2 behave and add
references to libpath in config.sys. I don't edit config.sys either if I
can avoid it, but I do if the readme explicitly state it.

2015-08-10 23:26 GMT+02:00 Dmitriy Kuminov <notifications@github.com>:

**Comment by dmik** [comment] 2015-08-10 23:33
The problem is that many conventional OS/2 installers (including OS/2 system installers) modify config.sys directly and therefore may reshuffle dir order in LIBPATH. There is no universal solution. What happens in eCS 2.2 Beta II Install (IIRC) is that it installs some system component after bootstrapping RPM and this order can't be easily changed. As I said, there is only one proper solution: use RPM for everything.

**Comment by dmik** [comment] 2015-08-12 18:11
From what I also see in the code, they switched to C++11 mode. This means that a lot of #ifdefs supporting older compilers are gone. I hope this will not result into too many build break on OS/2 (but there will be some due to missing defines, for sure — those are easily fixable though).

**Comment by dmik** [comment] 2015-08-13 17:29
A small bunch of files is left that were patched by me but deleted upstream. I need to figure out if these patches are still relevant and move them to a new location.

**Comment by dmik** [comment] 2015-08-13 21:18
Oops, missed with the browser tab. Moved last two comments to #115.
