### ISSUE TITLE
FF 38.8 crashes hard on 2e or 3rd downloading files

### ISSUE THREAD

**Issue by JoopN** [bitwiseworks/mozilla-os2#187] opened 2016-08-15 16:43 UTC
I had hoped that this would be in the past. Unfortunately its not. Now I had a hard crash, but report was on. 

[008A_01_TRAP_repot.txt](https://github.com/bitwiseworks/mozilla-os2/files/418490/008A_01_TRAP_repot.txt)

**Comment by dmik** [comment] 2016-08-15 17:02
The trap is in PMCTLS.DLL, it doesn't look directly related to Firefox at first sight. Perhaps, some other WPS/PM enhancer is interfering with it in some unusual way. You also use the very old EXCEPTQ which may generate inaccurate reports. Please:

1. Update to the latest one available in our RPM repositories (http://rpm.netlabs.org/release/00/zip/exceptq-7_11_3-1_oc00.zip).
2. Extract XUL.DBG from https://github.com/bitwiseworks/mozilla-os2/releases/download/FIREFOX_38_8_0esr_RELEASE_OS2_Beta_7/firefox-dbgsym-38.8.0.en-US.os2.zip and put it along with XUL.DLL.
3. Re-reproduce the trap again and attach a new trap file here.

**Comment by JoopN** [comment] 2016-08-16 15:30
Downloaded the two files and installed as instructed. Restart FF 38.8.0. On second download it halts, nothing works anymore. So I think that the trapfile doesn't have all, but I'm not sure, there is no " End of Exception Report" message. 
Here it is, it looks different now.
[008D_01.TRP.txt](https://github.com/bitwiseworks/mozilla-os2/files/420634/008D_01.TRP.txt)

**Comment by JoopN** [comment] 2016-08-16 16:06
Same behavior as before, second download system halts. Only way is reboot. Again a trap file was made, but again I don't know if its complete, no "End of Exception Report" line.
Here it is, second one, looks about the same as the first.
[0046_01.TRP.txt](https://github.com/bitwiseworks/mozilla-os2/files/420723/0046_01.TRP.txt)

**Comment by JoopN** [comment] 2016-08-16 16:21
Without downloading and only uploading the file here and some search on Github I did get on closing the browser some beeps from the system. I could find a new trap report, here it is.
[0046_09.TRP.txt](https://github.com/bitwiseworks/mozilla-os2/files/420749/0046_09.TRP.txt)

**Comment by dmik** [comment] 2016-08-16 22:38
Unfortunately these trap reports are completely useless. They are from unrelated threads (being terminated by the system because of the crash on the guilty thread). Somehow you should catch that. So please try again. If you still fail, try to downgrade EXCEPTQ to one of earlier versions, e.g. this one http://home.earthlink.net/%7Esteve53/betas/exceptq-7.11.2-shl-2015-08-29.zip.

**Comment by StevenLevine** [comment] 2016-08-17 02:39
Joop, it appears that you have configured EXCEPTQ to report normal terminations.  Check that you don't have the Z option set in the EXCEPTQ environment variable.  Exceptq does not generate .trp files for C0010001 or C0010002 exceptions unless requested by the user.  If you don't get a .trp file after this, it's possible that the exception is occurring at a location where Exceptq will not get control.  Start firefox using Run! and have Run! capture a log file.

**Comment by dryeo** [comment] 2016-08-17 04:55
Look in popuplog.os2 as well. The RPM/YUM version of NSPR4 seems to like 
writing there instead of creating trps.

**Comment by dmik** [comment] 2016-08-17 07:01
@StevenLevine thanks for the clarification, I had an impression that we shouldn't normally get these.

**Comment by JoopN** [comment] 2016-08-17 14:31
Op 17-08-16 06:55, Dave Yeo schreef:
> Look in popuplog.os2 as well. The RPM/YUM version of NSPR4 seems to like
> writing there instead of creating trps.
>
>
No, nothing there, lots of JAVA.EXE, but that's normal for me because I 
test a lot of Java programs and not all are for our OpenJDK or do have 
stuff for the other OS systems.

**Comment by JoopN** [comment] 2016-08-17 14:48
Op 17-08-16 04:39, StevenLevine schreef:
> Joop, it appears that you have configured EXCEPTQ to report normal terminations.
Check that you don't have the Z option set in the EXCEPTQ environment 
variable.
Exceptq does not generate .trp files for C0010001 or C0010002 exceptions 
unless
requested by the user.  If you don't get a .trp file after this, it's 
possible that
the exception is occurring at a location where Exceptq will not get 
control.
Start firefox using Run! and have Run! capture a log file.
>
Thanks Steve for the reminder. But the Z option is set and Run is set 
with the option EGL. I'm afraid I have done everything to get the stuff 
out for what's wrong. FF is going down very very fast. As soon as you 
hit the button your staring at your desktop instead of a screen from FF. 
And I'm after this for many years now! The only thing I could add is 
that when I'm in Cad-Popup screen I still see lines from actions which 
where done before. Like it didn't finish a task, but I can't make a 
screenprint from that because almost nothing works anymore, certainly 
not PMView.

**Comment by SilvanScherrer** [comment] 2016-08-17 14:57
@JoopN did you read what Steven wrote? The Z option should not be set.

**Comment by JoopN** [comment] 2016-08-17 16:05
Op 17-08-16 16:57, Silvan Scherrer schreef:
> @JoopN did you read what Steven wrote? The Z option should not be set.
>
Oeps..

**Comment by JoopN** [comment] 2016-08-17 17:42
Op 17-08-16 16:57, Silvan Scherrer schreef:
> @JoopN did you read what Steven wrote? The Z option should not be set.
>
I remmed the line, but with the third program on download hard crash, 
but no report.

**Comment by StevenLevine** [comment] 2016-08-18 04:29
As I asked before, what is in the log written by Run!.

@JoopN you need to keep in mind that you are the only one that can actually see what is happening on your system.  It's OK to not understand what we ask you to do.  It's not OK to not understand and not ask for clarification.

I notice you are still missing the kLIBC debug symbols.  You need to install them with yum or get the from www.warpcave.com/symbols.

**Comment by JoopN** [comment] 2016-08-18 19:17
Op 18-08-16 06:29, StevenLevine schreef:
Thanks Steve for your answer;

> As I asked before, what is in the log written by Run!.

This;
DIVE forced on by MOZ_ACCELERATED=1 - pointer will be hidden
Changing DIVE from enabled to disabled - 'layers.acceleration.disabled' 
is TRUE
Fontconfig warning: ignoring nl_NL_EURO: not a valid region tag
console.error:
   [CustomizableUI]
   Custom widget with id loop-button does not return a valid node
console.error:
   [CustomizableUI]
   Custom widget with id loop-button does not return a valid node

FIREFOX.EXE:
Abnormal program termination
RWSCLI08: RwsExitListProc - termination code= 0

FIREFOX.EXE:
Abnormal program termination


This is of no help. Exept that font config don't understand Dutch.


>
> @JoopN you need to keep in mind that you are the only one that can actually see what is

happening on your system.  It's OK to not understand what we ask you to 
do.  It's not OK

to not understand and not ask for clarification.

That's clear, sometimes its confusing.
>
> I notice you are still missing the kLIBC debug symbols.  You need to install them with

yum or get the from www.warpcave.com/symbols.
>
All of them?
I have now two, Doscalls and libc66.

Regards
Joop

**Comment by JoopN** [comment] 2016-08-18 19:56
Steven;

Op 18-08-16 06:29, StevenLevine schreef:

> I notice you are still missing the kLIBC debug symbols.

I have downloaded "doscall1.dll-sym-xqs-14.106smp.zip". Unpack it in the 
same directory as where doscall1.dll resides?

Joop

**Comment by wztest** [comment] 2016-09-04 19:45
@JoopN   Steve said klibc = libc, download libc066_xqs-sym-20141026.zip. Files should be in libpath (?).

**Comment by StevenLevine** [comment] 2016-09-04 20:06
@wztest - when using exceptq the .xqs or .sym files must be in the same
directory as the excutables.  This is true for most unattended debugging
tools, such as exceptq and some attended debugging tools, such as the
kernel debugger.

Attended tools like the OpenWatcom and VAC debugger default to looking for
debug data in the executable or the same directory as the executable. 
They can find debug data elsewhere, but this requires user intervention.

**Comment by SilvanScherrer** [comment] 2017-05-22 12:39
is this still true with Firefox 45?

**Comment by JoopN** [comment] 2017-05-25 07:55
Op 22-05-17 14:39, Silvan Scherrer schreef:
> is this still true with Firefox 45?
>
I didn't download FF45 yet.

Regards,
Joop

**Comment by SilvanScherrer** [comment] 2017-10-03 06:55
since no feedback and we can't reproduce it I close the issue. If it's still valid with version 45, please reopen.

**Closed by SilvanScherrer** 2017-10-03 06:55 UTC
Labels: awaiting feedback, tests

**Comment by JoopN** [comment] 2017-10-03 23:41
Silvan,

I'm sorry, but there was given enough feedback, but it seems not enough, 
you didn't do a thing with it. The whole bug system sucks. And I still 
can only download 2 files and FF crashes hard.
Due to issues with 45 I don't think I will use it.

Regards,
Joop Nijenhuis

Op  3-10-17 08:55, Silvan Scherrer schreef:
> since no feedback and we can't reproduce it I close the issue. If it's still valid with version 45, please reopen.
>

**Comment by SilvanScherrer** [comment] 2017-10-04 06:09
As we can't reproduce it with 45 and I even could not reproduce it with 38 there is no fix possible. And when you don't want to try 45 it's up to you. But we will for sure not invest time in pre 45 releases. I'm sorry about that.

**Comment by JoopN** [comment] 2017-10-06 08:20
Hello Silvian,

I understand that, but the bug procedure sucks. I asked what you want to 
see in the bug list, never got an answer. Yes, sometimes beep and a file 
with errors. But last time I got the message that the file was useless. 
So your program that create this bug list seems not up to the task. When 
I use such a program then it must produce a list which can be processed 
in a way that it fix problems and not in a message that its useless.

Regards,
Joop Nijenhuis

Op  4-10-17 08:09, Silvan Scherrer schreef:
> As we can't reproduce it with 45 and I even could not reproduce it with 38 there is no fix possible. And when you don't want to try 45 it's up to you. But we will for sure not invest time in pre 45 releases. I'm sorry about that.
>

**Comment by dmik** [comment] 2017-10-06 12:22
@JoopN It has been told several times what needs to be done to help us assist you with your problem. You need to get a meaningful .TRP report of your crash. So far you failed to do so despite all our advises. Once you succeed, we will be able to look further into your problem. So please try again.

1. Install the latest Firefox 45.9.0 GA
2. Install all the dependencies including the latest EXCEPTQ from RPM.
3. Make sure you don't have any custom EXCEPTQ setup (check your CONFIG.SYS, compare it to a freshly installed system if needed).
4. Make sure you don't have any custom Firefox setup. Check your CONFIG.SYS for any MOZ_ variables and also create a fresh Firefox profile for your test (just renaming `%MOZILLA_HOME%\Mozilla` to `%MOZILLA_HOME%\Mozilla.bak` will be enough; you will be able to rename it back once done with testing).

So far, everything suggests that your problem is related to some other 3rd party extension to WPS or PM which as nothing to do with Firefox itself. You can check if it's the case by installing a fresh copy of eCS 2.2+ or ArcaOS to a new partition and trying to reproduce your problem there (I'm sure you will not see it).
