### ISSUE TITLE
Another crash while loading page

### ISSUE THREAD

**Issue by michaelsnyder** [bitwiseworks/mozilla-os2#189] opened 2016-09-21 11:16 UTC
This crash happened after I disabled AdBlockPlus.  The page was not yet loaded, but some video on it was playing.  The page is www.pgatour.com.  ANPM says that my exceptq is up to date, but it reports itself as 7.11.3-shl in the trap file.
[00BA_01.txt](https://github.com/bitwiseworks/mozilla-os2/files/484817/00BA_01.txt)

**Comment by SilvanScherrer** [comment] 2016-09-21 11:24
this is the latest exceptq now.
Please do us a favor and don't open for every crash a new issue. As it's most likely a common cause.

**Comment by SilvanScherrer** [comment] 2016-09-21 11:25
similar as #183 and #184

**Comment by SilvanScherrer** [comment] 2017-05-22 12:33
is this still the case with Firefox 45?

**Comment by SilvanScherrer** [comment] 2017-10-03 06:51
since no feedback and we can't reproduce it I close the issue. If it's still valid with version 45, please reopen.

**Closed by SilvanScherrer** 2017-10-03 06:51 UTC
Labels: awaiting feedback, JavaScript, tests
