### ISSUE TITLE
Problems with import messages from PM Mail3

### ISSUE THREAD

**Issue by MattWalsh1** [bitwiseworks/mozilla-os2#182] opened 2016-07-13 21:57 UTC
With latest build 38-8 when I send an email over from PMMail3 apparently extra slashs get added to the URL and it won't go to site.  If I manually delete the extra slashes the address URL works.  This problem dioes not occur in similar trial with FireFox 31 for OS/2.  
Example: Message:  Firefox can't find the file at /E://temp//pmm-tmp//oa9wws00.html
but the URL line reads:   file:///E://temp//pmm-tmp//oa9wws00.html
Anyone else note this.

**Comment by LewisR** [comment] 2016-07-13 22:22
Matt, I think this is a dupe of #176. Please note David's specific mention of PMMail, in fact.

**Comment by SilvanScherrer** [comment] 2017-06-06 10:22
clearly a duplicate of #176, so closing this one

**Closed by SilvanScherrer** 2017-06-06 10:22 UTC
Labels: bug, duplicate
