### ISSUE TITLE
Cursor is not always visible

### ISSUE THREAD

**Issue by dryeo** [bitwiseworks/mozilla-os2#213] opened 2017-05-27 04:31 UTC
When writing a comment at eg os2world, often, especially when starting a new line, the cursor will not be visible. This affects Firefox and SeaMonkey.
This seems to be caused by AppConstants not always being imported, see bug#1231839.
Here's the patch (converted to git format)
```
From 0102573cd5df3d22aa059fe5d8334985c4d234bb Mon Sep 17 00:00:00 2001
From:  mossop <dtownsend@mozilla.com>
Date: Fri, 26 May 2017 20:06:43 -0700
Subject: [PATCH 2/2] Bug 1231839: Import AppConstants as needed

Signed-off-by: Dave Yeo <dave.r.yeo@gmail.com>
---
 toolkit/components/satchel/nsFormHistory.js | 2 ++
 1 file changed, 2 insertions(+)

diff --git a/toolkit/components/satchel/nsFormHistory.js b/toolkit/components/satchel/nsFormHistory.js
index 3407dd1348..2f4e0ece58 100644
--- a/toolkit/components/satchel/nsFormHistory.js
+++ b/toolkit/components/satchel/nsFormHistory.js
@@ -12,6 +12,8 @@ Components.utils.import("resource://gre/modules/Services.jsm");
 
 XPCOMUtils.defineLazyModuleGetter(this, "Deprecated",
                                   "resource://gre/modules/Deprecated.jsm");
+XPCOMUtils.defineLazyModuleGetter(this, "AppConstants",
+                                  "resource://gre/modules/AppConstants.jsm");
 
 const DB_VERSION = 4;
 const DAY_IN_MS  = 86400000; // 1 day in milliseconds
-- 
2.11.0
```

 that was applied to Firefox 46 but not back ported to FF45ESR.
Possibly this will also fix the form entry issue described in issue #128

Thanks to upstream, Frank-Rainer Grahl, SeaMonkey developer pointing out that this is needed to get close to a SM 2.42 release (it was never actually released)

**Comment by LewisR** [comment] 2017-05-27 06:04
Confirmed that I see this too, e.g., when entering a Mantis ticket. Very annoying. Unlike #128, however, I am able to access every form field. I just can't see an I-beam all the time (I have to click out and back in, or Ctrl-Left/Ctrl-Right to move the dumb cursor around).

**Comment by dmik** [comment] 2017-06-01 18:27
Unfortunately I can't reproduce the problem, neither with 45.5.0, nor with 45.9.0. But this in fact may be related to #208 (i.e. problems with timer messages which somehow get stuck in some cases or take much longer to fire than their nominal interval).

**Comment by dmik** [comment] 2017-06-01 18:48
Nevertheless, I committed this patch (see above) as it doesn't seem to do any harm. However I still think that what you see is related to timer issues rather than to a problem this patch fixes.

**Comment by dryeo** [comment] 2017-06-02 00:20
Thanks.
It does seem to have been another issue as Frank-Rainer says that this 
patch was for the Data Manager.
Anyways the cursor has been here consistently from when I first applied 
this patch.

**Comment by dmik** [comment] 2017-06-14 20:43
Please try a test build from #212 to reevaluate this issue as I have a feeling that it's completely gone now (a problem with mouse cursors was fixed there).

**Comment by SilvanScherrer** [comment] 2017-06-16 07:20
I could not see any such issues anymore, since #212 and #208 is fixed

**Comment by dmik** [comment] 2017-06-16 11:34
I guess that with #208 and #212 fixed this problem vanishes. Closing this. Reopen if not.

**Closed by dmik** 2017-06-16 11:34 UTC
Labels: bug, critical
