### ISSUE TITLE
38ESR incomplete session restore 

### ISSUE THREAD

**Issue by wztest** [bitwiseworks/mozilla-os2#161] opened 2016-02-29 20:09 UTC
The browser will sometimes crash when clicking on the link, in the case of restart the browser will not restore the set of tabs that was open before the crash (some are missing).  
The console log has tons of this message:

console.error: 
  Could not write session state file 
  Message: Unix error 0 during operation move on file G:\PROGRAMS\FIREFOX38_BETA6\Mozilla\Firefox\Profiles\1a241fcj.default\sessionstore-backups\recovery.js (Error 0)

\sessionstore-backups contains currently one file named recovery.js.tmp

**Comment by dmik** [comment] 2016-04-07 17:42
I can't reproduce this unfortunately. Here everything just works fine (including session restoring) after a kill/crash. Please try a new profile etc.

**Comment by SilvanScherrer** [comment] 2017-05-22 12:35
how does Firefox 45 behave?

**Comment by wztest** [comment] 2017-05-24 18:01
@SilvanScherrer  I hope that soon I can fix issue #201 then I'm able to open a web page to try this test, with session restore.

**Comment by SilvanScherrer** [comment] 2017-06-21 09:46
@wztest could you already do the tests? If not please try to do them asap.

**Comment by SilvanScherrer** [comment] 2017-10-03 06:48
as we can't reproduce it and no feedback from the reporter since end of May I close this issue.

**Closed by SilvanScherrer** 2017-10-03 06:48 UTC
Labels: awaiting feedback, tests
