### ISSUE TITLE
not possible to save dl files

### ISSUE THREAD

**Issue by 7865** [bitwiseworks/mozilla-os2#138] opened 2015-09-20 07:56 UTC
I recently tried to dl latest version of PMView
The file open dialogue opens. I select the save file option but the file save dialogue does not appear.
I have to go back to FF V24 in order to dl the file.
dc

**Comment by SilvanScherrer** [comment] 2015-10-22 09:19
what OS do you use? OS/2 or eCS. Using any WPS enhancer?

**Comment by 7865** [comment] 2015-10-22 12:43
OS is eCS V2.2 beta
Using NPS WPS enhancer

**Comment by SilvanScherrer** [comment] 2015-10-22 13:57
are the files not saved in your download directory? The download history (CTRL +J) also shows where it was downloaded.

**Comment by 7865** [comment] 2015-10-22 20:11
tried again with file from Hobbes.
file open screen has 'save file' selected. I push 'ok' and the screen  
disappears. In firefox 'options' I have 'always ask where to save files'  
selected, but the file save screen doesn't appear. I also changed the  
options to 'save file to downloads' and tried again. Alt-J does not show  
any file saved.
As i mentioned before firefox 24 works properly, firefox 31 does not.

**Comment by dryeo** [comment] 2015-10-22 23:48
Try moving or deleting downloads.sqlite from your profile directory with 
FF not running and retest

**Comment by StevenLevine** [comment] 2015-10-23 17:31
It's not clear if the OP tested with a new profile, but there's a known issue with content-prefs.sqlite
that can cause downloads to appear to fail more or less silently.  If content-prefs.sqlite has a bad path stored for a host, the Save dialog will not appear.  I assume that rather than ignoring the bad path, the save logic terminates.

My fix was to remove the bad path from content-prefs.sqlite.  In my case, I used the SQLite Manager to analyze the issue and delete the errant path.  Another option is move/delete content-prefs.sqlite .

One indicator that you have this problem is that a copy of the downloaded file will exist in the TMP directory with a temporary name.

**Comment by 7865** [comment] 2015-10-23 19:40
tried moving  downloads.sqlite and retested. Stillnot possible to view or  
download file from my internet banking site. The process works without  
problems when I use FF 24

**Comment by 7865** [comment] 2015-10-23 19:40
moved content-prefs.sqlite and tried another test. No improvement to the  
situation.
H:\var\temp has many files ending in .part from the days I've been testing.
Perhaps i should now put content-prefs.sqlite and downloads.sqlite back  
where they came from?

**Comment by StevenLevine** [comment] 2015-10-23 20:45
.part is the normal extension used for in progress downloads.  The rename happens when the file is moved to its final destination.  I recommend trying to figure out which are .zip files and using unzip -t to check if the file is complete and unsullied.  This will tell us whether the download itself is failing.

**Comment by dryeo** [comment] 2015-10-24 01:23
On 10/23/15 12:40 PM, 7865 wrote:
> Perhaps i should now put content-prefs.sqlite and downloads.sqlite back
> where they came from?

Not sure about content-prefs-sqlite, you can put downloads.sqlite back 
if you want to preserve your download history.
As Steven hinted at, have you tried a new profile? Firefox 
-profilemanger will allow you to create a new profile and switch between 
it and your old one.

**Comment by 7865** [comment] 2015-10-24 11:05
Yes, I just now started my 'test' profile but there were no positive  
results. ( file open dialogue fails to bring up the 'file save' dialogue  
box)

**Comment by 7865** [comment] 2015-10-24 11:20
ok I took the .part off one of the zip files. Using filestar/2 (which  
doesn't seeem to have an unzip -t option) I could view the file and see a  
list of the contents, but when I tried to unzip there was a black screen  
with streaming white text that appeared and quickly disappeared, but no  
results in the directory I set up to receive the files.
dc

**Comment by StevenLevine** [comment] 2015-10-24 14:54
Is it really that difficult to use unzip?  It should be in your ecs\bin directory?  While it appears that the download is corrupted, without the unzip -t output, I can only guess how the download is corrupted.  I would not asked for this information unless it was relevant.

**Comment by 7865** [comment] 2015-10-24 16:43
ok appologies for not figuring out what to do more quickly
here's the result

[H:\var\temp]unzip -t 42lkoBCz.zip
Archive:  42lkoBCz.zip
     testing: Animals/                 OK
     testing: Animals/CardInfo.TXT     OK
     testing: Animals/CardInfo.TXT.info   OK
     testing: Animals/CardPic.IFF      OK
     testing: Animals/CardPic.IFF.info   OK
     testing: Animals/CardPic_AGA.IFF   OK
     testing: Animals/CardPic_AGA.IFF.info   OK
     testing: Animals/CardSample-1.IFF   OK
     testing: Animals/CardSample-1.IFF.info   OK
     testing: Animals/CardSample-10.IFF   OK
     testing: Animals/CardSample-10.IFF.info   OK
     testing: Animals/CardSample-2.IFF   OK
     testing: Animals/CardSample-2.IFF.info   OK
     testing: Animals/CardSample-3.IFF   OK
     testing: Animals/CardSample-3.IFF.info   OK
     testing: Animals/CardSample-4.IFF   OK
     testing: Animals/CardSample-4.IFF.info   OK
     testing: Animals/CardSample-5.IFF   OK
     testing: Animals/CardSample-5.IFF.info   OK
     testing: Animals/CardSample-6.IFF   OK
     testing: Animals/CardSample-6.IFF.info   OK
     testing: Animals/CardSample-7.IFF   OK
     testing: Animals/CardSample-7.IFF.info   OK
     testing: Animals/CardSample-8.IFF   OK
     testing: Animals/CardSample-8.IFF.info   OK
     testing: Animals/CardSample-9.IFF   OK
     testing: Animals/CardSample-9.IFF.info   OK
     testing: Animals/SampleFinished.IFF   OK
     testing: Animals/SampleFinished.IFF.info   OK
     testing: Animals/SampleFound.IFF   OK
     testing: Animals/SampleFound.IFF.info   OK
No errors detected in compressed data of 42lkoBCz.zip.

**Comment by StevenLevine** [comment] 2015-10-24 21:55
The unzip -t results indicate that the download completed without errors
and the problem is with moving the file to its final destination.

Since this is failing with a fresh profile, I have to suspect you have a
backleveled component that is affecting firefox.

How did you install the firefox pre-requisites?  Yum/rpm or using the
required DLLs zip file method?

Although it is probably unrelated, I'm curious as to what is wrong with
your filestar setup.  The unzip -t rusults indicate it should have had no
problems handling this zip file.

**Comment by 7865** [comment] 2015-10-25 17:47
rpm/yum no longer works so I used the required DLLs zip file method.
filestar unzip worked, it just put the files in  a sub directory that I  
didn't notice until after writing to you.
I'll go through the readme and check that everything wound up in the right  
place.
dc

**Comment by dryeo** [comment] 2015-10-25 21:16
On 10/25/15 10:47 AM, 7865 wrote:
> rpm/yum no longer works so I used the required DLLs zip file method.
> filestar unzip worked, it just put the files in a sub directory that I
> didn't notice until after writing to you.
> I'll go through the readme and check that everything wound up in the right
> place.

The important thing is that there are no downlevel DLLs that are earlier 
in your LIBPATH.
Easiest test is to use BEGINLIBPATH and LIBPATHSTRICT to make sure the 
required DLLs are loaded first and see if you still have the issue.

**Comment by SilvanScherrer** [comment] 2015-10-26 09:29
when yum/rpm is no longer working, I bet you have a libc and other dll problem. And as long as this is not fixed it's very likely, that firefox behaves strange.
As you have ecs, please move your unixroot/usr/lib before ecs/dll in the libpath statement. And then I'm almost sure yum/rpm works again. If you don't like to move unixroot/usr/lib infront of ecs/dll, you need to find all duplicated dll in those 2 directories and remove the older ones from ecs/dll.

**Comment by 7865** [comment] 2015-10-27 18:21
Many thanks for this. I moved usr/lib in the libpath and its now possible  
to dl monthly account statements in pdf from the banking site.
Along the way I re-read some of the readme's and realized I should have  
used warp-in to de-install the Yum bootstrap. Did this. Perhaps it is now  
ok to delete the tmp directories?

tried Yum, but it now gives a different error message, as follows:

>>>There was a problem importing one of the Python modules
required to run yum. The error leading to this problem was:

    No module named urlgrabber

Please install a package which provides this module, or
verify that the module is installed correctly.

It's possible that the above module doesn't match the
current version of Python, which is:
2.7.6 (default, Feb 26 2015, 18:19:11)
[GCC 4.9.2]

If you cannot solve this problem yourself, please go to
the yum faq at:
   http://yum.baseurl.org/wiki/Faq

**Comment by SilvanScherrer** [comment] 2015-10-27 18:32
The entries in tmp can be deleted, but not the tmp dir itself.
And for the urlgrabber problem see: http://trac.netlabs.org/rpm/ticket/77
I close this issue here, as it's fixed. If yum/rpm still doesn't work after the urlgrabber fix, please open a ticket at http://trac.netlabs.org/rpm.

**Closed by SilvanScherrer** 2015-10-27 18:32 UTC
Labels: bug
