### ISSUE TITLE
Trap while attempting to download update from Arca Noae

### ISSUE THREAD

**Issue by michaelsnyder** [bitwiseworks/mozilla-os2#184] opened 2016-08-01 20:59 UTC
From the list of my downloads, I clicked on the USB driver.  The program left the attached trap file.  Upon a restart of Firefox, I was able to download the file without a trap.
[0294_01.TXT](https://github.com/bitwiseworks/mozilla-os2/files/394766/0294_01.TXT)

**Comment by SilvanScherrer** [comment] 2016-09-20 09:25
similar as #187

**Comment by michaelsnyder** [comment] 2016-09-20 13:36
On 09/20/16 at 02:25 AM, Silvan Scherrer <notifications@github.com> said:


>similar as #187 

Yes, I get lots of these.  Do you want reports of them or are the ones
that I've already sent sufficient to describe the problem?

-- 
_________________________________________________________________________
"Politics is the art of looking for trouble, finding it everywhere, diagnosing it incorrectly and applying the wrong remedies. - Groucho Marx
"Islamophobia: that last look of fear in your eyes just before your head comes off." - Donna Driscoll November 16, 2015

Mike Snyder
msnyder1@cfl.rr.com

**Comment by SilvanScherrer** [comment] 2016-09-21 08:22
unfortunately we can't reproduce the crashes so far. Do you have some special wps enhancers installed? Or some plugins?
Please also upate to latest exceptq either via "yum update exceptq" or ANPM and attach a new trap file

**Comment by SilvanScherrer** [comment] 2017-05-22 13:03
please try with Firefox 45

**Comment by SilvanScherrer** [comment] 2017-10-03 06:51
since no feedback and we can't reproduce it I close the issue. If it's still valid with version 45, please reopen.

**Closed by SilvanScherrer** 2017-10-03 06:51 UTC
Labels: awaiting feedback, tests
