### ISSUE TITLE
mozilla-media-cache is never cleaned

### ISSUE THREAD

**Issue by an64** [bitwiseworks/mozilla-os2#39] opened 2014-01-16 23:40 UTC
Firefox leaves all temporary media files in the mozilla-media-cache directory

Also its will be nice to have some environment variable to specify location of this directory, eg i'm like  %temp%\mozilla-media-cache , as in the 10.x branch , not inside the profile , as in the 17

**Comment by dmik** [comment] 2015-03-04 18:09
Hmm, I must be doing something wrong. I can't see any media cache with my last build of FF (24.8.1). Neither in profile nor in temp. What should I do to get it?

**Comment by dmik** [comment] 2015-03-04 18:20
Got it. Signing in to gmail and opening some PDF in your inbox creates `mozilla-temp-XXX` in `%TEMP%`. And it's not deleted indeed.

**Comment by abwillis** [comment] 2015-03-04 20:35
I believe that is a separate (though maybe related) problem.  The media cache is i directory called:  mozilla-media-cache    Mine is in the profile directory and one in the temp directory.
I just opened mine and found a 200M file from September.   Then the names of the files under that directory are media-cache and then -1, -2, etc.
The issue you are seeing, I suspect, is the one where the temp files that are created are created read only.  Not sure that is why they are not cleaned up but it is what I have suspected.

**Comment by abwillis** [comment] 2015-03-04 20:39
One other thing I am noticing in the several places I actually find the media-cache files.  They are all older.  I am not finding any newer ones here.  Seeings I don't know how/why/when they are created I am not sure if that is significant or not.

**Comment by dmik** [comment] 2015-03-04 21:18
Hmm, you are right. sorry. Then I have no idea on how to get these `mozilla-media-cache` files created. I see none of them no matter what I do. Can you give me a recipe?

**Comment by dmik** [comment] 2015-03-04 22:48
BTW, the `mozilla-temp` files are not deleted not because they are read/only. the `DELETE_ON_CLOSE` option is implemented on OS/2 the same way as on Unix — by attempting to delete the file right after opening it. But on Unix this causes the file to be actually deleted when it's closed while on OS/2 this just always fails because an open file cannot be deleted.

Luckily, we have the `urpo` library from Yuri Dario that re-implements `unlink` in a way that provides the same functionality as on Unix. I will try to use it in the implementation of `PR_Delete` in NSPR instead of `DosDelete`, that should help.

BTW, on Windows they use a different approach. They put all temporary files into a single directory that is cleared by a background task at browser startup.

**Comment by dmik** [comment] 2015-03-05 00:04
Okay, the `unlink` approach didn't work. Perhaps, the file still remains open by the time when the LIBC atexit hooks are called, because it is open with `DosOpen`, not with `open`. I'm not going to debug into this, I will try the Windows approach.

**Comment by dspiatkowski** [comment] 2015-03-05 01:39
In my current install (FF 17.0.11esr) I have over 2Gig worth of cache files in \HOME\mozilla.org\userprofiles\Mozilla\Firefox\Profiles\q5xd2gmv.default\mozilla-media-cache location. These keep on growing.

There is also the \HOME\mozilla.org\userprofiles\Mozilla\Firefox\Profiles\q5xd2gmv.default\Cache folder, but this appears to have old stuff in it...files here are dated at least 3 years ago...so I suspect FF 17.x is not writing there.

Occasionally FF will also create files in the \tmp\mozilla-media-cache directory. Somehow this one is always cleaned up, I rarely find anything there. The Profile folder on the other hand just keeps on growing....

**Comment by an64** [comment] 2015-03-05 02:39
mozilla-media-cache its a cache for webm playback, so simply open any html5 video to get these

**Comment by dmik** [comment] 2015-03-06 00:14
@an64, still, no `mozilla-media-cache` here after playing HTML5 videos on YouTube for quite a while. Any other suggestions?

**Comment by dmik** [comment] 2015-03-06 01:09
Anyway, in 35dcd06c56a9dddd6ae1fb194bb7cd9db0a2dbd8 I enabled the Windows approach for temporary files created with `nsAnonymousTemporaryFile` and it seems to work. However this would delete temporary files only at startup while it makes sense to do so during the whole browser session (at idle times) and also try to do it at shutdown. I implemented this in 0569869b34b182a115db6be32319f95c6b5a7d75.

Cleaning up temporary files at shutdown may fail though because some files may be still open by that time. This will also fail if the browser crashes. But anyway, these files will be deleted once it is started again (just as in the original Windows approach).

**Comment by dmik** [comment] 2015-03-06 01:10
I also searched for `meda-cache` through the current source tree and didn't find this combination in any of the source files. This suggests that if someone has these files, they are created not by mozilla itself (maybe by some extension etc). If I'm not given a good way to reproduce this behavior within the next few days, I will have to leave it as is and will close this issue as resolved.

**Comment by dryeo** [comment] 2015-03-06 03:16
On 03/05/15 05:10 PM, Dmitriy Kuminov wrote:
> I also searched for |meda-cache| through the current source tree and
> didn't find this combination in any of the source files.

They were created by older versions of Mozilla, I used to see them in 
%TEMP% and copy them to somewhere else to watch later or save.
Looking in the Firefox 17esr tree, I see /content/media/nsMediaCache.cpp 
and xpcom/io/nsMediaCacheRemover.cpp which have gone away in 24esr.

**Comment by dmik** [comment] 2015-03-06 09:44
Okay, I checked the FF17 sources. Indeed, the old cache lived in `content/media/nsMediaCache.cpp` and they used to manually create `mozilla-media-cache` files. In FF24 this file was renamed to `MediaCache.cpp` and now they use `nsAnonymousTemporaryFile` (that deals with these new `mozilla-temp-XXX` files) instead of creating temporary files manually. My feeling is that `nsAnonymousTemporaryFile` (and the current version of `nsMediaCacheRemover`) is the end of evolution of their attempts to solve the problem of temporary media cache files not being deleted on Windows (where DELETE_ON_CLOSE doesn't always work).

A more elegant solution on OS/2 would be to enhance LIBC so that it automatically deletes files `unlink`-ed while being open (to mimic Unix behavior) when they are closed or when the LIBC process terminates. This way we'd get them deleted instantly rather than at some periods of time when the browser is running. However, this requires a) LIBC fixes and b) porting of NSPR to LIBC (it now uses Dos* API). But that's just for the record. Perhaps we will do that when we take some the version of Firefox where OS/2 support is completely cut off. This `unlink` solution will not solve the problem of temporary files being left over after an unexpected shutdown of the computer but there is another solution to that: clean the TEMP directory on boot (which successfully works here so that I did never notice the media cache problem myself). But that's another story.

Anyway, this issue is considered to be done now.

**Closed by dmik** 2015-03-06 09:44 UTC
Labels: task, tests
