### ISSUE TITLE
Umlauts are garbled in FF OS/2 when using FF sync with Windows machines

### ISSUE THREAD

**Issue by herwigb** [bitwiseworks/mozilla-os2#165] opened 2016-03-16 16:52 UTC
When using German umlauts in bookmark menus these get garbled, when FF sync is enabled and other machines are using FF for Windows.

**Comment by SilvanScherrer** [comment] 2016-03-21 11:49
I bet issue #162 and this issue have a lot in common. Could you see if Windows does a real Unicode Format?

**Comment by herwigb** [comment] 2016-03-21 15:08
How to do that?

**Comment by herwigb** [comment] 2017-06-22 14:05
Tests I did:
- Create FF OS/2 Bookmark (without Umlauts) -> sync to FF Win works
- Create FF Win Bookmark (without Umlauts) -> Sync to FF OS/2 works
- Create FF OS/2 Bookmark with Umlauts -> FF Win only sees the original name (="New bookmark")
- Create FF Win Bookmark with Umlauts -> FF OS/2 sees it but with garbled Umlauts

The garbled Umlauts look as if an UTF-8 Umlaut was not decoded, but displayed directly.

**Comment by herwigb** [comment] 2017-06-22 15:15
@SilvanScherrer and me tested the same scenario between a FF Linux, FF Win and FF OS/2 bookmarks.
Umlauts can be shared between FF Linux and FF Win, neither FF Linux nor FF Win see bookmarks with Umlauts created on FF OS/2. FF OS/2 see Umlauts created be FF Win or FF Linux garbled.

**Comment by herwigb** [comment] 2017-06-22 15:41
https://github.com/bitwiseworks/mozilla-os2/blob/master/intl/locale/os2/nsOS2Charset.cpp

**Comment by dmik** [comment] 2017-08-04 16:54
I can reproduce this with Cyrillic of course.

**Comment by dmik** [comment] 2017-08-04 19:44
Hard to say what happens so far. But the code above doesn't seem to be involved. The whole `nsPlatformCharset` thingy is marked as deprecated. It's now assumed that all platforms use UTF-8 everywhere (including prefs, bookmarks and plain text files). However, the OS/2 still thinks it's encoded in its local charset and tries to first encode in it then decode from it which gives such strange results.

The original mozilla ticket related to this issue is https://bugzilla.mozilla.org/show_bug.cgi?id=943272

**Comment by dmik** [comment] 2017-08-04 22:16
Studying places.sqlite shows that local bookmarks are saved there in UTF-8 (as they should).  Which means that the problem pops up when transferring them to Firefox Sync over the wire. My guess it that OS/2 converts them from UTF-8 to a native charset when sending and from the native charset to UTF-8 when receiving.

The native charset data received by the Firefox Sync server is interpreted as UTF-8 and results in invalid sequences for chars >0x7F so it doesn't get stored there at all (my case, cyrillic right from the beginning) or gets stored with the original name if it's latin only (Herwig's case). And vice versa: the UTF-8 data received from the Firefox Sync server on the OS/2 side is interpreted as it's in the native charset so it gets encoded into UTF-8 the second time. So when it's then decoded from UTF-8 in the UI it looks like a raw UTF-8 string (since it was an UTF-8 string from the beginning). This is what both I and Herwig see.

**Comment by dmik** [comment] 2017-08-07 15:13
This is the developer's description of Firefox Sync BTW: https://wiki.mozilla.org/Services/Sync.

**Comment by dmik** [comment] 2017-08-07 21:36
My current (and proven) finding is that OS/2 properly reports Unicode to the JS side (`services/sync` in the source tree) responsible for encrypting Firefox Sync data and sending it over to the server. So misconversion happens somewhere in this this encrypt/send/receive/decrypt pipeline. I'm going through it step by step but it's not fast since there are many layers and since JS is weakly typed per se so any code may be anywhere.

Still, looks like some stream/buf is interpreted as it's native on OS/2 at some point while it's actually utf-8.

**Comment by dmik** [comment] 2017-08-08 15:00
I guess I know where the problem is. It's DEEP inside, argh. The sync JS code at some point uses `ArrayType` from js-ctypes (which is a ctypes JS wrapper to interface with C libraries) to create a `unsigned char` array out of the UCS2 (Unicode) string which all java strings are. The sync code assumes that this operation will involve converting UCS2 to UTF-8 and this is what happens on all other platforms indeed. However, on OS/2, IIRC, creating such an array will convert UCS2 to a native codepage which was done because native C functions on OS/2 (such as the ones in LIBC) expect `unsigned char` strings to be in the native codepage.

This, of course breaks everything in sync code for characters greater than 0x7F. Note that ASCII  (simple Latin) characters work fine with sync since they are represented as is in all codepages including UTF-8.

A general fix might be not easy as we can't change the LIBC code page separately from the process code page and changing the process code page to UTF-8 will I'm sure break a lot of things here and there. As a workaround, I will try to use something else but ctypes in sync code and see where it leads me.

**Comment by dmik** [comment] 2017-08-08 15:49
BTW, the respective commits that make ctypes interpret `char` C strings as containing native code page data instead of UTF-8 is affe4be76621ca9930608952c5bd937cff68039b, 995cecf1f275d9f6d308053f6a99a84135df9f18, 6d0725893193754b296a854d305dd5a50b67df61, a0c0fef0d18740351fa0488ab8882200c99eb66f. (There may be more).

**Closed** 2017-08-09 20:52 UTC
Labels: enhancement, tests

**Comment by dmik** [comment] 2017-08-09 22:37
@herwigb Should be fixed now. This also fixes synchronizing tabs and everything else (which was broken too because it uses the same sync/crypto engine).

A new test build of FF is available at http://rpm.netlabs.org/test/yb9p4.7z. Please note that it's not easy to recover from the wrongly synchronized bookmarks on the OS/2 side because a corrupted text is already cached locally — you have to alter each problematic bookmark on a Windows machine to cause a resync of it (FF sync limitation — there is no way to tell it to simply take a new copy of the remote bookmark and overwrite the local data).

**Comment by dmik** [comment] 2017-08-09 23:03
Regarding the fix. I had to add explicit UTF-8 <-> Unicode translation for JS strings before passing them to C code (NSS/crypt/etc). And this is how it should have been done from the very beginning instead of relying on JS ctypes wrappers interpreting 1-byte char C arrays as UTF-8 (which is not always the case, at least not on OS/2).
