### ISSUE TITLE
Loading Google Maps leads to error on loading map

### ISSUE THREAD

**Issue by lerdmann** [bitwiseworks/mozilla-os2#273] opened 2018-06-27 05:54 UTC
Using latest 45.9.0.
I get this error (in the web console):
"You have exceeded your daily request quota for this API. We recommend enabling billing to get a higher quota: https://developers.google.com/maps/documentation/javascript/usage"

when I try to load this page (in case it matters):
https://bayern.jugendherberge.de/jugendherbergen/wunsiedel-280/lage-und-anreise/

What the heck does that mean ?

**Comment by dryeo** [comment] 2018-06-27 06:09
Google isn't giving away unlimited access to their maps API and 
bayern.jugendherberge.de needs to pay to keep displaying maps?

**Comment by lerdmann** [comment] 2018-06-27 08:21
The page displays fine with other browsers and therefore it is not an issue of the content provider but of the browser. And then, the error message might be misleading. I think it is rather related to javascript not working properly. In fact, the map briefly shows up until the above error pops up in the web console.

Could you properly display the page, or rather, the map part of it (selecting the "Lage & Anreise" button) ?

**Comment by SilvanScherrer** [comment] 2018-06-27 12:09
I used this link https://bayern.jugendherberge.de/jugendherbergen/wunsiedel-280/lage-und-anreise/ thats also the one you posted. And the map looks good. No message or whatever.

**Comment by dspiatkowski** [comment] 2018-06-27 12:26
...same here, map comes up fine, I am able to zoom in/out as needed, and  
since I use NoScript  to allow all the different servers access I had to  
cycle through the map (automatic) several times, all without any problems.

**Comment by dryeo** [comment] 2018-06-27 14:41
Last night (here) when you first posted, it would only partly display 
before switching to an error message. Today it is displaying fine.
Never saw the error message that you did, perhaps due to using SeaMonkey.

**Comment by lerdmann** [comment] 2018-06-28 05:57
The error message on the page itself is different, it says something 
like you have a problem with Java.

It is the WEB CONSOLE that shows the error message that I first mentioned.
And strange enough, today the map shows just fine. I wonder if that was 
a temporary page problem or if there is some timing issue with Firefox.

Lars

**Comment by dryeo** [comment] 2018-06-28 06:21
On 06/27/18 10:57 PM, lerdmann wrote:
> And strange enough, today the map shows just fine. I wonder if that was
> a temporary page problem or if there is some timing issue with Firefox.

I had the same problem with SeaMonkey and Thunderbird. I'd assume it was 
a problem with the server.

**Comment by SilvanScherrer** [comment] 2018-06-28 13:36
as not reproducible anymore I close this issue.

**Closed as completed by SilvanScherrer** 2018-06-28 13:36 UTC
