### ISSUE TITLE
FF 31.8.0 can't process locale add-ons

### ISSUE THREAD

**Issue by JoopN** [bitwiseworks/mozilla-os2#117] opened 2015-07-25 13:08 UTC
Vendor=Mozilla
Name=Firefox
Version=31.8.0
BuildID=20150724032810

Tried to update my locale, but there seems to be a problem. Tried it with downloading file and open file with menu and tried it via the add-ons option. Both fail.
![Uploading bug002.jpg…]()

**Comment by StevenLevine** [comment] 2015-07-26 06:45
Downloaded and installed nederlands_nl_language_pack-31.0-fx.xpi
 here and it appears to work fine.

I noticed one defect, but it is cross-platform.  Disabling the language pack from the Add-ons dialog while leaving the locale set to "nl" does not switch everything back to English.

**Comment by JoopN** [comment] 2015-07-26 20:32
Hello Steve,

Don't know where you get that file, the file I see comes from the 
windows directory and then the xpi directory. The file there is called 
nl.xpi and is for switching the language of the browser, not for writing 
something, that are other language packs.

When i open the file and click on the install button then I get the 
message "XXX could not be installed because Firefox cannot modify the 
needed file". Tried it too with the Locale Switcher, so the XXX are 
replaced with Locale Switcher.

Don't have an idea where to look for. The error message doesn't give 
much help.
I installed exceptq, but it doesn't do a thing. Also the readme is not 
up to what's in the package. So I'm unsure if I did the right things.

Regards
Joop




Op 26-07-15 08:45, StevenLevine schreef:

**Comment by StevenLevine** [comment] 2015-07-26 21:58
>Don't know where you get that file,

It came from

  https://addons.mozilla.org/en-us/firefox/language-tools/

where you can find all the supported dictonaries and language packs.

>I installed exceptq, but it doesn't do a thing.

That's exactly what it should do, unless firefox throws an exception.

>Also the readme is not 
>up to what's in the package. So I'm unsure if I did the right things.

Which readme?  Do you read exceptq-shl.txt, which states:

 "This document is an addendum to the exceptq.txt and readme.exceptq
documents included in the 7.1 releases."

Did you try to run any of the installation validation tests in the \tests
directory?

**Comment by JoopN** [comment] 2015-07-26 23:54
Thaks Steve for your time,

Op 26-07-15 23:58, StevenLevine schreef:
>
>> Don't know where you get that file,
>
> It came from
>
>    https://addons.mozilla.org/en-us/firefox/language-tools/
>
> where you can find all the supported dictonaries and language packs.
>

Thanks, I go there some time.

>> I installed exceptq, but it doesn't do a thing.
>
> That's exactly what it should do, unless firefox throws an exception.
>
Okay

>> Also the readme is not
>> up to what's in the package. So I'm unsure if I did the right things.
>
> Which readme?  Do you read exceptq-shl.txt, which states:
>
>   "This document is an addendum to the exceptq.txt and readme.exceptq
> documents included in the 7.1 releases."
>
The readme.exceptq, it is very unclear what to copy to the dll directory.


> Did you try to run any of the installation validation tests in the \tests
> directory?
>
No, have to read how to proceed.

Regards,
Joop

**Comment by JoopN** [comment] 2015-07-27 00:08
I have it now Dutch, but its not done in the way it should. I have 
inspected a few xpi files, there are in fact just zip files, one of the 
first characters are pk from Phil Katz, inventor of zip. So with FC/2 I 
could open the files and see what's in it. Nothing special. Next I 
inspected a few versions what they do.

Next I copied the nl.xpi to the file 
langpack-nl@firefox.mozilla.org.xpi. Copied from the older version of FF 
the file {338e0b96-2285-4424-b4c8-e2556}.xpi (locale switcher 3) to the 
directory extensions.

Start FF, go to Tools>Add-ons>Languages. Enable language pack. Exit FF. 
Restart FF, go to Tools>Add-ons>Extensions, enable locale switcher 3, 
exit FF. Restart FF, go to Tools>Languages, choose Dutch, exit FF. 
Restart FF and you have Dutch menu's and help etc.

But this is far from normal. It shows however that it works, so the 
problem is narrowed down to that FF can't proceed with installation.

Regards,
Joop



Op 26-07-15 08:45, StevenLevine schreef:

**Comment by JoopN** [comment] 2015-07-27 00:20
Op 26-07-15 23:58, StevenLevine schreef:
> Did you try to run any of the installation validation tests in the \tests
> directory?

Yes, I run the exceptq-test-* files, have 3 trp files in same directory.

Regards,
Joop

**Comment by StevenLevine** [comment] 2015-07-27 04:45
>I have inspected a few xpi files, there are in fact just zip files,

I'm a tad confused.  What did you expect them to be? They have been this way since Mozilla extensions were invented.

>Nothing special.

What did install.rdf in your nl.xpi indicate that the acceptable Firefox versions were?

problem is narrowed down to that FF can't proc

Unless there is something wrong with your setup, Firefox will install the language pack (nederlands_nl_language_pack-31.0-fx.xpi) that I pointed you to without errors because it is designed to install on version 38.x.

**Comment by dmik** [comment] 2015-07-27 16:59
@JoopN If I understand you right you say that 31 Beta 5 can't install locale XPI files. Unfortunately, I can't test it because I can't find any official source of locale XPI files where I could take a file to try. The files available on the official add ons page are only for Firefox 39 (are not supposed to be compatible with Firefox 31).

If you provide more detailed steps on how to reproduce your issue and I will try.

BTW, your screenshot didn't show up here because you most likely pressed the Comment button too early, before the file was uploaded. Please try to re-upload it.

**Comment by dmik** [comment] 2015-07-27 17:13
I found a way how to download the right version of the language pack. Go to https://addons.mozilla.org/en-us/firefox/language-tools/, select the necessary language then scroll down to the bottom of the page, expand the **Version Information** box, press the **See complete version history** link find your version there (31 in our case) and then press the **Add to Firefox** button.

I tried it locally and installing the Russian locale worked brilliantly here. I had to manually set the `general.useragent.locale` setting in `about:config` to `ru-RU` and restart to get it fully working (including the main menu) but that's the limitation of the Firefox distribution. I also tried the Dutch locale and it also worked well (after setting `general.useragent.locale` to `nl`).

Closing this as everything works here. Feel free to re-open if you find anything still not working.

**Closed by dmik** 2015-07-27 17:13 UTC

**Comment by JoopN** [comment] 2015-07-28 00:10
Op 27-07-15 06:45, StevenLevine schreef:
>> I have inspected a few xpi files, there are in fact just zip files,
>
> I'm a tad confused.  What did you expect them to be? They have been this way since Mozilla extensions were invented.
>

Sorry, just described the way what I've done.

>> Nothing special.
>
> What did install.rdf in your nl.xpi indicate that the acceptable Firefox versions were?

<em:maxVersion>31.*</em:maxVersion>
>

> problem is narrowed down to that FF can't proc
>
> Unless there is something wrong with your setup, Firefox will install the language pack (nederlands_nl_language_pack-31.0-fx.xpi) that I pointed you to without errors because it is designed to install on version 38.x.
>

As you can see above I doubt that.

**Comment by JoopN** [comment] 2015-07-28 00:20
Op 27-07-15 18:59, Dmitriy Kuminov schreef:
> @JoopN If I understand you right you say that 31 Beta 5 can't install locale XPI files. Unfortunately, I can't test it because I can't find any official source of locale XPI files where I could take a file to try. The files available on the official add ons page are only for Firefox 39 (are not supposed to be compatible with Firefox 31).

I always used 
ftp://ftp.mozilla.org/pub/mozilla.org/firefox/releases/31.8.0esr/win32/xpi/ 
and then you have to choose your locale file, for me that's nl.xpi
>
> If you provide more detailed steps on how to reproduce your issue and I will try.

Download the xpi file. Go to FF and file>>open file. FF comes up with a 
popup screen if you want to install. Yes, and then you get the message 
that it has problems.

>
> BTW, your screenshot didn't show up here because you most likely pressed the Comment button too early, before the file was uploaded. Please try to re-upload it.

Sorry, system for uploading hangs for some reason.

**Comment by JoopN** [comment] 2015-07-28 00:28
Op 27-07-15 19:13, Dmitriy Kuminov schreef:
> I found a way how to download the right version of the language pack. Go to https://addons.mozilla.org/en-us/firefox/language-tools/, select the necessary language then scroll down to the bottom of the page, expand the **Version Information** box, press the **See complete version history** link find your version there (31 in our case) and then press the **Add to Firefox** button.

Tried this, but it ended with same message. Can't proceed because FF 
can' adjust necessary file.

> I tried it locally and installing the Russian locale worked brilliantly here. I had to manually set the `general.useragent.locale` setting in `about:config` to `ru-RU` and restart to get it fully working (including the main menu) but that's the limitation of the Firefox distribution. I also tried the Dutch locale and it also worked well (after setting `general.useragent.locale` to `nl`).
>
> Closing this as everything works here. Feel free to re-open if you find anything still not working.

That's too soon for closing.

**Comment by StevenLevine** [comment] 2015-07-28 02:09
@JoopN, I tested the version from the FTP site.  It's a bit older than the version @dmik pointed you to and the content has minor differences.  However, it installs fine here.

Have you tried with a fresh, test profile?

**Comment by dmik** [comment] 2015-07-28 18:48
A comment from @JoopN in #122:

Deleted installation of FF31.8.0 and reinstall it again. Tried the installation outlined by Dmitriy. I get this in the log file;

DIVE forced on by MOZ_ACCELERATED=1 - pointer will be hidden
_init_dive: _load_dive() succeeded
_init_dive: hDive= 1 scrn= 0x4ab0000 format= BGR4
Changing DIVE from enabled to disabled - 'layers.acceleration.disabled' is TRUE
console.error: 
Could not write session state file 
I:\FIREFOX_3180\Mozilla\Firefox\Profiles\9x7wfvrt.default\sessionstore.js
Message: Unix error 0 during operation move on file I:\FIREFOX_3180\Mozilla\Firefox\Profiles\9x7wfvrt.default\sessionstore.js (Error 0)
1438048091321 addons.repository WARN Unknown type id when parsing addon: 5
1438048096712 addons.xpi WARN Failed to install E:\var\temp\tmp-czm.xpi from https://addons.mozilla.org/firefox/downloads/file/268076/nederlands_nl_language_pack-31.0-fx.xpi?src=version-history: {"operation":"stat","path":"I:\FIREFOX_3180\Mozilla\Firefox\Profiles\9x7wfvrt.default\extensions\staged\langpack-nl@firefox.mozilla.org.xpi","unixErrno":0}

Fresh install, new profile. As its working for you it must be something outside FF, which file (dll) will cause this if its missing or if version is not right?

**Comment by dmik** [comment] 2015-07-28 18:49
@JoopN what OS/2 version do you have? Are you sure you have only one `lbc065.dll` on your drive? What is the timestamp of it? What other software do you have running when this happens? Looks like there is indeed some mess with DLLs on your system.

**Comment by StevenLevine** [comment] 2015-07-29 00:48
>Could not write session state file 
>I:\FIREFOX_3180\Mozilla\Firefox\Profiles\9x7wfvrt.default\sessionstore.js
>Message: Unix error 0 during operation move on file

Makes me wonder if @JoopN has a backleveled version of urpo.dll.

FWIW, there are also multiple versions of stdcpp6.dll out there.  However,
firefox would not even start here until I updated to the 2015-02-02 build,
so this is unlikely to be the problem here.

**Comment by JoopN** [comment] 2015-07-29 19:32
eCS1.2 Dutch, 23-03-12, there is a libc066.dll 26-10-14 as well. Can't 
unlock libc065.dll, don't know what program locks it after fresh restart.

Op 28-07-15 20:49, Dmitriy Kuminov schreef:

**Comment by JoopN** [comment] 2015-07-29 19:36
Is it possible that libs065 and libc066 are the cause, got one mail from 
someone else in Holland with same problem, he switched libc but my 
libc065 is locked. Asked how to unlock.


Op 29-07-15 02:48, StevenLevine schreef:

**Comment by dmik** [comment] 2015-07-29 19:56
Yes, it's most likely the reason of your problem. Please make sure that you ONLY have one set of libc06* DLLs with the following timestamps (time may differ in several hours due to timezone differences):
```
  48179 Oct 26  2014 libc06.dll
  48179 Oct 26  2014 libc061.dll
 157161 Oct 26  2014 libc062.dll
 157161 Oct 26  2014 libc063.dll
 157213 Oct 26  2014 libc064.dll
 157213 Oct 26  2014 libc065.dll
1361666 Oct 26  2014 libc066.dll
```
You should rename any other `libc06*` DLLs you find on your drive to something like `libc065.dll.disabled` or simply zip them up and delete. If any of these DLLs is locked, you may unlock it with
```
unlock filename.dll
```
before deleting and reboot afterwards. When rebooted, double check that there are no other DLLs except the ones listed above.

**Comment by JoopN** [comment] 2015-07-29 20:48
Thanks, two where wrong. Replaced. Updating to Dutch did work now, so 
that problem is solved. However, downloading is not. Download a file 
without extension like readme. You get a popup screen with save download 
as or similar message and with okay nothing happens. Also open the file 
with a program is greyed out. Unfortunately no log file, no trp file. It 
just hangs.


Op 29-07-15 21:56, Dmitriy Kuminov schreef:

**Comment by dmik** [comment] 2015-07-29 20:50
Please create a new issue for the download problem and provide the screenshot and the exact download link so that we could test.
