### ISSUE TITLE
Trap on opening a PDF file with FF 31.8.0

### ISSUE THREAD

**Issue by GAnchieri** [bitwiseworks/mozilla-os2#136] opened 2015-08-28 09:35 UTC
I wan to view a PDF file, but in opening the file I receive a trap (three different trap for the same pdf)
that I attach to this issue.
http://gist.github.com/GAnchieri/1046825564a58d53d1d5

**Comment by SilvanScherrer** [comment] 2015-09-03 13:43
do all pdf files trap? or only some? I use this feature regulary and I can't see any problems with it.

**Comment by GAnchieri** [comment] 2015-09-04 08:28
For me as I can remember, only this PDF file give this trap, I don't know if other PDF can do this many variety of trap.
If you can determine the type of instruction in error analyzing  this trap, OK, otherwise I don't know  how help you with other PDF.
Thank you for your interest in resolving bug under firefox.
Your G.M. Anchieri

**Comment by SilvanScherrer** [comment] 2015-09-04 11:08
to see what it could be, it would help to get our hands on the failing pdf.

**Comment by GAnchieri** [comment] 2015-09-05 09:11
After a day of search on my bookmark, I have retrieved the pdf in error, here is the link to this page:
http://www3.ao-legnano.it/SiteAssets/Lists/CercaPersone/EditForm/Licastro%20Giovanni%20Maria.pdf
I receive the msg: 403 forbidden and then the trap.
G.M. Anchieri

**Comment by SilvanScherrer** [comment] 2015-10-22 09:21
btw does this pdf work on other platform? Could you eventually test?

**Comment by GAnchieri** [comment] 2015-10-22 13:27
I can view it (it's of 9(nine) page) using firefox version 40/41 that run under VBOX 1.6.0 on my eCS 2.2 
b1.  
Unfortunately I don't can upload the file because it's a *.pdf file and your system refuse to upload it.
G.M.Anchieri

**Comment by SilvanScherrer** [comment] 2015-10-22 13:54
ok so please retry after ffox 38 is out. If it still crashes we will ask for the pdf.

**Comment by GAnchieri** [comment] 2016-02-22 17:20
After installing the new version of FF 38.2.1 I have retested this link and now I receive a dialog that invite me to download this PDF file. 
I'm expected to view it directly using FF method of viewing PDF files as usual and not to download it for viewing with  lucide or other program, and so for me, this ticket isn't resolved perfectly.

**Comment by dmik** [comment] 2016-02-24 09:34
I can NOT confirm this issue. When I load the above URL, Firefox 38.2.1 opens a buillt-in PDF viewer in a new tab. This is true for 31.8.2 as well though. 

@GAnchieri most likely, your environment is broken somehow. Please try to create a new profile for Firefox and retry. The easiest way to try with the new profile is to rename your old profile dir `path_to_profile` to `path_to_profile.bak` — Firefox will create a new one at startup. After testing, you can delete `path_to_profile` and rename `path_to_profile.bak` back to it to restore your normal settings.

Anyway, I'm closing it as not a bug. Feel free to re-open if you find any evidence that it's still a bug of Firefox.

**Closed by dmik** 2016-02-24 09:34 UTC
Labels: bug, JavaScript

**Comment by GAnchieri** [comment] 2016-02-27 15:19
Hi dmik, I have uncovered why this can happen. In "Options" window in applications bar exist the Portable Document Format (PDF) entry with three possibility: 1) Save File, 2) Preview in Firefox, 3) Always ask,
with Save File set by default.
After setting this application as Preview in Firefox all returned as stated and I can view this PDF in FF.
Thank you,
G.M. Anchieri.
